.PHONY: clean All

All:
	@echo "----------Building project:[ algorithm_debug - Debug ]----------"
	@"$(MAKE)" -f  "algorithm_debug.mk"
clean:
	@echo "----------Cleaning project:[ algorithm_debug - Debug ]----------"
	@"$(MAKE)" -f  "algorithm_debug.mk" clean
