.PHONY: clean All

All:
	@echo "----------Building project:[ parse_max30102_data - Debug ]----------"
	@cd "parse_max30102_data" && "$(MAKE)" -f  "parse_max30102_data.mk"
clean:
	@echo "----------Cleaning project:[ parse_max30102_data - Debug ]----------"
	@cd "parse_max30102_data" && "$(MAKE)" -f  "parse_max30102_data.mk" clean
